version: "3.0"

services:

  django:

    build: django
    container_name: django_server
    restart: always
    volumes:
      - ./django:/usr/src/app
    ports:
      - "80:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:

    image: postgres:latest
    container_name: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: django
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker_data/pg_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache_server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${R_PASSWORD}
    volumes:
      - ./docker_data/redis_data:/data